### PR TITLE
Some changes

### PR DESCRIPTION
**Pull request by Langsdorf**

### CODE REVIEW

**Comment by rutgerkok** [comment]
@Langsdorf 

Thanks for all your contributions!

If you want, I can give you write access to the repo, so that you don't need our approval beforehand.

**Comment by Langsdorf** [comment]
@rutgerkok 

I would like it! Thanks!

**Comment by ZINGDING** [comment]
@Langsdorf 
Congratulation! :)

**Comment by rutgerkok** [comment]
I added you to the project! Good luck, @Langsdorf!

**Pull request merged**
