### PR TITLE
Implement a lot of methods in PokkitWorld

### PR DESCRIPTION
**Pull request by MrPowerGamerBR**

### CODE REVIEW

**Comment by MrPowerGamerBR** [comment]
@rutgerkok now I have an question:

If a method doesn't exist in Nukkit/MCPE, can we send fake information to the plugin?

Example: isInsideVehicle(), Nukkit doesn't have proper vehicle implementation yet and there isn't any API to get the player's vehicle, so it would be better to just return false instead of throwing an exception.

If it would be bad to do that, could a config option be added to enable this "feature"? I'm asking this because WorldBorder is "almost" working in Pokkit with my changes, however I'm now stuck because WorldBorder requests isInsideVehicle() and I don't know if I should just return false or keep the exception.

**Comment by ZINGDING** [comment]
I think that's a good opinion!

**Comment by rutgerkok** [comment]
Agreed. The goal of Pokkit is to get Bukkit plugins working on Nukkit. In the case of isInsideVehicle, `return false;` is simply the best implementation we can do.

We need to look at each method separetely to determine what would be the best implementation. `throw Pokkit.unsupported()` is only useful when the plugin would break anyways (but then with a more confusing error message). I also use it for methods that I haven't reviewed at all, so that I immediately know what I need to implement to get a plugin working.

A config option is not needed in my opinion. Why would we add an option to break plugins?

**Comment by rutgerkok** [comment]
@MrPowerGamerBR 

Anyways, thanks for submitting all these pull request!

If you want, I can give you access to this repo, so that you can just change the code yourself.

**Comment by MrPowerGamerBR** [comment]
@rutgerkok whoa! I would be very grateful if you gave me write access to Pokkit's repo :)

**Comment by rutgerkok** [comment]
I sent an invite.

Pokkit is one of those projects that works best with a lot of contributors. The project has just one goal (getting Bukkit plugins working on Nukkit), the code structure is also set in stone (we have to follow the Bukkit API), so there is very little chance that someone steps on someone else's toes.

**Pull request merged**
